name: build_push

on: [push]

jobs:
  run_molecule_test:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        distro:
          - image: unbound
            version: "1.12.0"
            tags: "1.12.0"
          - image: unbound
            version: "1.13.0"
            tags: "1.13.0"
          - image: unbound
            version: "1.14.0"
            tags: "1.14.0"
          - image: unbound
            version: "1.15.0"
            tags: "1.15.0"
          - image: unbound
            version: "1.16.0"
            tags: "1.16.0"
          - image: unbound
            version: "1.17.0"
            tags: "1.17.0,latest"
    uses: hybridadmin/reuse-workflows/.github/workflows/build_push.yml@main
    secrets: inherit
    with:
      distro_image: '${{ matrix.distro.image }}'
      distro_tags: '${{ matrix.distro.tags }}'
      distro_platform: 'linux/amd64,linux/arm64' #'${{ matrix.distro.platform }}'
      distro_version: '${{ matrix.distro.version }}'

  run_update_readme:
    needs:
      - run_molecule_test
    uses: hybridadmin/reuse-workflows/.github/workflows/update_readme.yml@main
    secrets: inherit
    with:
      repo_name: 'hybridadmin/unbound'
