name: build_push

on: [push]

jobs:
  run_molecule_test:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        distro:
          - image: unbound
            version: "1.20.0"
            tags: "1.20.0"
          - image: unbound
            version: "1.21.0"
            tags: "1.21.0"
          - image: unbound
            version: "1.22.0"
            tags: "1.22.0"
          - image: unbound
            version: "1.23.0"
            tags: "1.23.0"
          - image: unbound
            version: "1.24.0"
            tags: "1.24.0,latest"
    uses: hybridadmin/reuse-workflows/.github/workflows/build_push_apps.yml@main
    secrets: inherit
    with:
      distro_image: '${{ matrix.distro.image }}'
      distro_tags: '${{ matrix.distro.tags }}'
      distro_platform: 'linux/amd64,linux/arm64'
      distro_version: '${{ matrix.distro.version }}'
      skip_tests: 'true'

  run_update_readme:
    needs:
      - run_molecule_test
    uses: hybridadmin/reuse-workflows/.github/workflows/update_readme.yml@main
    secrets: inherit
    with:
      repo_name: 'hybridadmin/unbound'
