name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - image: unbound
            version: "1.12.0"
            tags: "1.12.0"
            platform: "linux/amd64"
          - image: unbound
            version: "1.13.0"
            platform: "linux/amd64"
            tags: "1.13.0"
          - image: unbound
            version: "1.14.0"
            platform: "linux/amd64"
            tags: "1.14.0"
          - image: unbound
            version: "1.15.0"
            platform: "linux/amd64"
            tags: "1.15.0"
          - image: unbound
            version: "1.16.0"
            platform: "linux/amd64"
            tags: "1.16.0"
          - image: unbound
            version: "1.17.0"
            platform: "linux/amd64"
            tags: "1.17.0,latest"


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/Push Docker to DockerHub
        run: |
          docker buildx build \
            --push \
            --platform ${{ matrix.distribution.platform }} \
            --file=${{ matrix.distribution.version }}/Dockerfile \
            $(for i in $(echo ${{ matrix.distribution.tags }} | sed "s/,/ /g"); do echo "--tag hybridadmin/${{ matrix.distribution.image }}:$i "; done) \
            .

  update_readme:
    needs:
      - build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Repo Readme/Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: hybridadmin/unbound
          readme-filepath: ./README.md
