name: ci

on:
  push:
    branches: main

jobs:
  multi-builders:
    runs-on: ubuntu-latest
    steps:
      -
        uses: docker/setup-buildx-action@v1
        id: builder1
      -
        uses: docker/setup-buildx-action@v1
        id: builder2
      -
        name: Builder 1 name
        run: echo ${{ steps.builder1.outputs.name }}
      -
        name: Builder 2 name
        run: echo ${{ steps.builder2.outputs.name }}
      -
        name: Build against builder1
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
#          target: mytarget1
          file: ./1.13.0/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: false
          tags: |
            hybridadmin/unbound:latest
            hybridadmin/unbound:1.13.0
      -
        name: Build against builder2
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder2.outputs.name }}
#          target: mytarget2
          file: ./1.12.0/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: false
          tags: |
            hybridadmin/unbound:1.12.0
